#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data_utils import load_image, load_mask


def main() -> None:
    parser = argparse.ArgumentParser(description='Export preprocessed EWS samples to compressed NPZ files.')
    parser.add_argument('csv_index', type=Path, help='Path to a split CSV generated by build_index.py')
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'processed', help='Where NPZ files should be written.')
    parser.add_argument('--color-space', choices=['rgb', 'gray', 'hsv', 'lab'], default='rgb')
    parser.add_argument('--no-normalize', action='store_true', help='Do not scale image pixels to [0, 1].')
    parser.add_argument('--limit', type=int, default=None, help='Optional limit for quick testing.')
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    with args.csv_index.open('r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if args.limit is not None:
        rows = rows[: args.limit]

    for row in rows:
        image = load_image(Path(row['image_path']), color_space=args.color_space, normalize=not args.no_normalize)
        mask = load_mask(Path(row['mask_path']), as_binary=True)
        out_path = args.output_dir / f"{Path(row['image_name']).stem}.npz"
        np.savez_compressed(
            out_path,
            image=image.astype(np.float32),
            mask=mask.astype(np.uint8),
            split=row['split'],
            image_name=row['image_name'],
            mask_name=row['mask_name'],
            color_space=args.color_space,
            normalized=not args.no_normalize,
        )
        print(f'Saved {out_path}')


if __name__ == '__main__':
    main()
