#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import random
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data_utils import load_image, load_mask


def overlay_mask(image: np.ndarray, mask: np.ndarray, alpha: float = 0.35) -> np.ndarray:
    if image.max() <= 1.0:
        base = (image * 255).astype(np.uint8).copy()
    else:
        base = image.astype(np.uint8).copy()
    overlay = base.copy()
    overlay[mask > 0] = np.array([255, 0, 0], dtype=np.uint8)
    return ((1 - alpha) * base + alpha * overlay).astype(np.uint8)


def main() -> None:
    parser = argparse.ArgumentParser(description='Create sanity-check visualisations for a split CSV.')
    parser.add_argument('csv_index', type=Path, help='Path to a split CSV generated by build_index.py')
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'examples' / 'sanity_checks')
    parser.add_argument('--num-samples', type=int, default=6)
    parser.add_argument('--seed', type=int, default=42)
    args = parser.parse_args()

    with args.csv_index.open('r', encoding='utf-8') as f:
        rows = list(csv.DictReader(f))

    if not rows:
        raise ValueError('CSV index is empty.')

    random.seed(args.seed)
    chosen = random.sample(rows, k=min(args.num_samples, len(rows)))

    args.output_dir.mkdir(parents=True, exist_ok=True)

    for row in chosen:
        image = load_image(Path(row['image_path']), color_space='rgb', normalize=False)
        mask = load_mask(Path(row['mask_path']), as_binary=True)
        overlaid = overlay_mask(image, mask)

        fig, axes = plt.subplots(1, 3, figsize=(12, 4))
        axes[0].imshow(image.astype(np.uint8))
        axes[0].set_title('RGB image')
        axes[1].imshow(mask, cmap='gray')
        axes[1].set_title('Binary mask')
        axes[2].imshow(overlaid)
        axes[2].set_title('Overlay')
        for ax in axes:
            ax.axis('off')
        fig.suptitle(row['image_name'])
        fig.tight_layout()
        out_path = args.output_dir / f"{Path(row['image_name']).stem}_sanity.png"
        fig.savefig(out_path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        print(f'Saved {out_path}')


if __name__ == '__main__':
    main()
